version: 2

jobs:
  build:
    docker:
      - image: clojure:alpine

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "auth/project.clj" }}
          - v1-dependencies-
      - run: cd auth && lein deps && cd ..
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "auth/project.clj" }}

  test:
    docker:
      - image: clojure:alpine

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "auth/project.clj" }}
          - v1-dependencies-
      - run: cd auth && lein test && cd ..

workflows:
  version: 2
  test_analysis:
    jobs:
      - build
      - test:
          requires:
            - build
